name: Cryptic Bot

repo:
  owner: PyDrocsid
  name: CrypticBot
  icon: "https://github.com/Defelo.png"

author: Defelo

languages:
  - en
default_language: en

roles:
  admin:
    name: Administrator
    check_assignable: false

  head:
    name: Head
    check_assignable: false

  head_assistant:
    name: Head Assistant
    check_assignable: false

  server_admin:
    name: Server Admin
    check_assignable: false

  frontend:
    name: Frontend
    check_assignable: true

  backend:
    name: Backend
    check_assignable: true

  qm:
    name: Quality Management
    check_assignable: true

  gamedesign:
    name: Gamedesign
    check_assignable: true

  design:
    name: Design
    check_assignable: true

  website:
    name: Website
    check_assignable: true

  social_media:
    name: Social Media
    check_assignable: true

  wiki:
    name: Wiki
    check_assignable: true

  security:
    name: Security
    check_assignable: true

  correction:
    name: Correction
    check_assignable: true

  text:
    name: Text
    check_assignable: true

  translator:
    name: Translator
    check_assignable: true

  notification:
    name: Notification
    check_assignable: true

  mute:
    name: Mute
    check_assignable: true

permission_levels:
  administrator:
    name: Administrator
    level: 3
    aliases: [admin, a]
    if:
      permissions: [administrator]
      roles: [admin]

  head:
    name: Head
    level: 2
    aliases: [h]
    if:
      roles: [head]

  head_assistant:
    name: Head Assistant
    level: 1
    aliases: [headassistant, ha]
    if:
      roles: [head_assistant]

default_permission_level: administrator
default_permission_overrides:
  sudo:
    clear_cache: owner
    reload: owner
    stop: owner
    kill: owner

teamler_level: head_assistant
