version: '3.9'


services:
  bot:
    image: pydrocsid/bot
#   image: pydrocsid/bot:develop
    restart: always
    tty: true
    env_file: bot.env
    depends_on:
      - db
      - redis
    networks:
      - bot

  db:
    image: mariadb
#   image: jsurf/rpi-mariadb
    restart: always
    env_file: bot.env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - bot

  redis:
    image: redis:alpine
    restart: always
#   volumes:
#     - ./data/redis:/data
    networks:
      - bot

networks:
  bot:
